@startuml context
!includeurl https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
Person(user, "User of vehicle management system")

System_Boundary(system, "Vehicle Management System") {
    Container(server, "Server", "F#, ASP.NET, Equinox, Propulsion, Fable.Remoting", "Handles requests")
    Container(spa, "SPA", "F#, Fable, React")
    ContainerDb(cosmos, "CosmosDB", "Stores raw events and read models")
}

Rel(user, server, "Requests site", "HTTP")
Rel(user, spa, "Interacts with site")
Rel(server, spa, "Serves static files", "HTTP")
Rel(spa, server, "Sends messages to; Receives messages from", "Websocket")
Rel(server, cosmos, "Stores events in; Reads events from", "TCP")

@enduml