@startuml reactor
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

ContainerDb(eventstore, "EventStoreDB", "Stores raw events")
ContainerDb(redis, "Redis", "Stores 'Vehicle Count' read model")
ContainerDb(litedb, "LiteDB", "Stores 'Vehicle Overview' read model")
Container_Boundary(reactor, "Reactor") {
    Component(subscription, "EventStoreDBSubscription", "Manages EventStore subscription")
    Component(cache, "RedisCache", "Interacts with")
    Component(documentStore, "LiteDBDocumentStore", "Interacts with LiteDB")
    Component(vehicleOverview, "VehicleOverviewReactor", "Maintains 'Vehicle Overview' read model")
    Component(vehicleCount, "VehicleCountReactor", "Maintains 'Vehicle Count' read model")
    Rel(vehicleOverview, subscription, "Creates new")
    Rel(vehicleCount, subscription, "Creates new")
    Rel(vehicleOverview, documentStore, "Updates 'Vehicle Overview' using")
    Rel(vehicleCount, cache, "Updates 'Vehicle Count' using")
}
Rel(subscription, eventstore, "Receives events from", "TCP")
Rel(cache, redis, "Interacts with", "TCP")
Rel(documentStore, litedb, "Interacts with", "IO")
@enduml