version: '3.7'

services:
  server:
    build:
      context: .
      dockerfile: ./docker/server.Dockerfile
      args:
        RUNTIME_ID: linux-x64
    environment:
      SECRETS_DIR: /var/secrets
    ports:
      - "5000:5000"
    volumes:
      - c:/dev/secrets/ameier38/cosmosdb:/var/secrets/cosmosdb
  reactor:
    build:
      context: .
      dockerfile: ./docker/reactor.Dockerfile
      args:
        RUNTIME_ID: linux-x64
    environment:
      SECRETS_DIR: /var/secrets
      HUB_URL: "http://server:5000/hub"
    volumes:
      - c:/dev/secrets/ameier38/cosmosdb:/var/secrets/cosmosdb
