version: '3.7'

services:
  app:
    build:
      context: .
      args:
        RUNTIME_ID: linux-x64
    environment:
      APP_ENV: dev
      SECRETS_DIR: /var/secrets
    ports:
      - "5000:5000"
    volumes:
      - c:/dev/secrets/ameier38/cosmosdb:/var/secrets/cosmosdb